export const mockDatas = [
    {
        name: "Personal information",
        fields: [
            {
                id: "firstname",
                required: true,
                label: "First name",
                type: "text",
                maxLength: 127,
            },
            {
                id: "lastname",
                required: true,
                label: "Last name",
                type: "text",
                maxLength: 127,
            },
            {
                id: "email",
                required: true,
                label: "Email",
                type: "email",
                maxLength: 255,
            },
            {
                id: "headline",
                required: false,
                label: "Headline",
                type: "text",
                maxLength: 255,
            },
            {
                id: "phone",
                required: false,
                label: "Phone",
                type: "phone",
                helper: "The hiring team may use this number to contact you about this job.",
                maxLength: 255,
            },
            {
                id: "address",
                required: false,
                label: "Address",
                type: "text",
            },
            {
                id: "avatar",
                required: false,
                label: "Photo",
                type: "file",
                supportedFileTypes: [".jpg", ".jpeg", ".gif", ".png"],
                supportedMimeTypes: ["image/jpeg", "image/gif", "image/png"],
                maxFileSize: 12000000,
            },
        ],
    },
    {
        name: "Profile",
        fields: [
            {
                id: "education",
                required: false,
                label: "Education",
                type: "group",
                fields: [
                    {
                        id: "school",
                        required: true,
                        label: "School",
                        type: "text",
                        maxLength: 255,
                    },
                    {
                        id: "field_of_study",
                        required: false,
                        label: "Field of study",
                        type: "text",
                        maxLength: 255,
                    },
                    {
                        id: "degree",
                        required: false,
                        label: "Degree",
                        type: "text",
                        maxLength: 255,
                    },
                    {
                        id: "start_date",
                        required: false,
                        label: "Start date",
                        type: "date",
                    },
                    {
                        id: "end_date",
                        required: false,
                        label: "End date",
                        type: "date",
                    },
                ],
            },
            {
                id: "experience",
                required: false,
                label: "Experience",
                type: "group",
                fields: [
                    {
                        id: "title",
                        required: true,
                        label: "Title",
                        type: "text",
                        maxLength: 255,
                    },
                    {
                        id: "company",
                        required: false,
                        label: "Company",
                        type: "text",
                        maxLength: 255,
                    },
                    {
                        id: "industry",
                        required: false,
                        label: "Industry",
                        type: "text",
                        maxLength: 255,
                    },
                    {
                        id: "summary",
                        required: false,
                        label: "Summary",
                        type: "paragraph",
                    },
                    {
                        id: "start_date",
                        required: false,
                        label: "Start date",
                        type: "date",
                    },
                    {
                        id: "end_date",
                        required: false,
                        label: "End date",
                        type: "date",
                    },
                    {
                        id: "current",
                        required: false,
                        label: "I currently work here",
                        type: "boolean",
                    },
                ],
            },
            {
                id: "summary",
                required: false,
                label: "Summary",
                type: "paragraph",
            },
            {
                id: "resume",
                required: false,
                label: "Resume",
                type: "file",
                supportedFileTypes: [".pdf", ".doc", ".docx", ".odt", ".rtf"],
                supportedMimeTypes: [
                    "application/pdf",
                    "application/msword",
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                    "application/vnd.oasis.opendocument.text",
                    "application/rtf",
                ],
                maxFileSize: 12000000,
            },
        ],
    },
    {
        name: "Details",
        fields: [
            {
                id: "cover_letter",
                required: false,
                label: "Cover letter",
                type: "paragraph",
            },
            {
                id: "QA_7197549",
                required: true,
                label: "Test paragraph?",
                type: "paragraph",
            },
            {
                id: "QA_7197550",
                required: true,
                label: "Test short answer",
                type: "text",
                maxLength: 127,
            },
            {
                id: "QA_7197551",
                required: true,
                label: "Test yes/no with disqualify on asnwer no",
                type: "boolean",
            },
            {
                id: "QA_7197552",
                required: true,
                label: "Test dropdown answer",
                type: "dropdown",
                options: [
                    {
                        name: "3547804",
                        value: "anser1",
                    },
                    {
                        name: "3547805",
                        value: "answer 2",
                    },
                    {
                        name: "3547806",
                        value: "answer 3",
                    },
                ],
                singleOption: true,
            },
            {
                id: "QA_7197553",
                required: true,
                label: "Test MC question(only one answer allowed)",
                type: "multiple",
                options: [
                    {
                        name: "3547807",
                        value: "choice 1",
                    },
                    {
                        name: "3547808",
                        value: "choice 2",
                    },
                    {
                        name: "3547809",
                        value: "choice 3",
                    },
                ],
                singleOption: true,
            },
            {
                id: "QA_7197554",
                required: true,
                label: "Test MC question",
                type: "multiple",
                options: [
                    {
                        name: "3547810",
                        value: "choice 1",
                    },
                    {
                        name: "3547811",
                        value: "choice 2",
                    },
                    {
                        name: "3547812",
                        value: "choice 3",
                    },
                ],
                singleOption: false,
            },
            {
                id: "QA_7197555",
                required: true,
                label: "Test Date",
                type: "date",
            },
            {
                id: "QA_7197556",
                required: true,
                label: "Test number",
                type: "number",
                max: 9999999999999,
            },
            {
                id: "QA_7197557",
                required: true,
                label: "Test file",
                type: "file",
                supportedFileTypes: [
                    ".pdf",
                    ".doc",
                    ".docx",
                    ".odt",
                    ".rtf",
                    ".ppt",
                    ".pptx",
                    ".png",
                    ".jpg",
                    ".jpeg",
                    ".gif",
                    ".tiff",
                    ".xlsx",
                    ".xls",
                    ".zip",
                ],
                supportedMimeTypes: [
                    "application/pdf",
                    "application/msword",
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                    "application/vnd.oasis.opendocument.text",
                    "application/rtf",
                    "application/vnd.ms-powerpoint",
                    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
                    "image/png",
                    "image/jpeg",
                    "image/gif",
                    "image/tiff",
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    "application/vnd.ms-excel",
                    "application/zip",
                ],
                maxFileSize: 20000000,
            },
        ],
    },
];
