import "./globals.scss";
import "react-quill/dist/quill.snow.css";
import "react-quill/dist/quill.bubble.css";
import type { Metadata } from "next";
import Script from "next/script";
import {
    Inter,
    Montserrat,
    Poppins,
    Public_Sans,
    Roboto_Mono,
} from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import dynamic from "next/dynamic";
import "nprogress/nprogress.css";

import ReduxProvider from "@/components/ReduxProvider/ReduxProvider";

const TopProgressBar = dynamic(
    () => import("@/components/TopProgressBar/TopProgressBar"),
    {
        ssr: false,
    }
);

const inter = Inter({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-inter",
});

const roboto_mono = Roboto_Mono({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-roboto-mono",
});
const publicSans = Public_Sans({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-public-sans",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={`${inter.className} ${roboto_mono.className} ${publicSans.className}`}
            >
                <ToastContainer
                    position="top-center"
                    autoClose={5000}
                    hideProgressBar={false}
                    newestOnTop={false}
                    closeOnClick
                    rtl={false}
                    pauseOnFocusLoss
                    draggable
                    pauseOnHover
                    theme="light"
                />
                <TopProgressBar />
                <ReduxProvider>{children}</ReduxProvider>
                <div id="hirelight__portal"></div>
                <Script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js" />
            </body>
        </html>
    );
}
