export const FETCH_EMAIL_TEMPLATES = "FETCH_EMAIL_TEMPLATES";
export const FETCH_EMAIL_TEMPLATE_TYPES = "FETCH_EMAIL_TEMPLATE_TYPES";
export const DELTE_EMAIL_TEMPLATES_BY_ID = "DELTE_EMAIL_TEMPLATES_BY_ID";
export const EDIT_EMAIL_TEMPLATE = "EDIT_EMAIL_TEMPLATE";
